version: 2
jobs:
  build:
    machine: true
    enviroment:
     CHECK_DOC: 0
     CHECK_LOGPRINT: 0
     BOOST_TEST_RANDOM: 1$TRAVIS_BUILD_ID
     CCACHE_SIZE: 100M
     CCACHE_TEMPDIR: /tmp/.ccache-temp
     CCACHE_COMPRESS: 1
     SDK_URL: https://bitcoincore.org/depends-sources/sdks
     WINEDEBUG: fixme-all
     RUN_TESTS: true
     BITCOIN_CONFIG: --enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER
    steps:
      - checkout
      - run:
          name: Set PATH
          command: export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
      - run:
          name: Update apt repo
          command: sudo apt-get update
      - run:
          name: Install packages
          command: sudo apt-get install --no-install-recommends --no-upgrade -qq bc python3-zmq
      - run:
          name: Unset
          command: unset CC; unset CXX
      - run:
          name: Mkdir
          command: mkdir -p depends/SDKs depends/sdk-sources && ls
      - run:
          name: Make libraries
          command: make -j3 -C depends HOST=x86_64-unknown-linux-gnu NO_QT=1 NO_UPNP=1 DEBUG=1
      - run:
          name: Set outdir
          command: OUTDIR=CIRCLE_WORKING_DIRECTORY/x86_64-unknown-linux-gnu
      - run:
          name: set Cache
          command: depends/x86_64-unknown-linux-gnu/native/bin/ccache --max-size=$CCACHE_SIZE
      - run:
          name: Autogen
          command: test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
      - run:
          name: Configure
          command: ./configure --cache-file=config.cache --disable-dependency-tracking --prefix=CIRCLE_WORKING_DIRECTORY/depends/x86_64-unknown-linux-gnu --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib --enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER || ( cat config.log && false)
      - run:
          name: Make direcotries
          command: make distdir PACKAGE=bitcoin VERSION=x86_64-unknown-linux-gnu
      - run:
          name: Enter directory
          command: cd bitcoin-x86_64-unknown-linux-gnu
      - run:
          name: Configure
          command: ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
      - run:
          name: Compile
          command: make -j3 install || ( echo "Build failure. Verbose build follows." && make install V=1 ; false )
      - run:
          name: export libraries
          command: export LD_LIBRARY_PATH=CIRCLE_WORKING_DIRECTORY/depends/x86_64-unknown-linux-gnu/lib
      - run:
          name: Run tests
          command: make -j3 check VERBOSE=1